### ISSUE TITLE
[Bug]: How to apply the script variant on website using CSS?

### ISSUE THREAD

**Issue by KoichaDev** [MonoLisaFont/feedback#293]
### Edition

Plus

### What version are you using?

2.015

### What type of weights are you using?

Variable (customized)

### Operating system

macOS, Windows

### What happened?

Hi,

I’m working on building my own personal usage Chrome extension to switch to the MonoLisa font, because it makes it much easier for me to focus and read.

I really like the font’s script variant feature, but unfortunately, I haven’t been able to get it to work. Despite selecting the custom variant on the order page and downloading it, I can only see the regular MonoLisa font.

Am I missing something in my CSS code? Below is a small snippet of the code I’m using for the regular font size:

```css
@font-face {
  src: local("MonoLisa"), local("MonoLisa Variable"),
    url(/assets/fonts/mono-lisa/MonoLisa-Regular.ttf) format("truetype");
  font-family: monolisa;
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}

@font-face {
  src: local("MonoLisa"), local("MonoLisa Variable"),
    url(/assets/fonts/mono-lisa/MonoLisa-RegularItalic.ttf) format("truetype");
  font-family: monolisa;
  font-weight: 400;
  font-style: italic;
  font-display: swap;
}
```

and I am using JS to toggle the font to make it work:

```js
...
const fontCSS = `
    body, p, li, h1, h2, h3, h4, h5, h6 {
      font-family: 'monolisa', sans-serif !important;
      font-style: italic !important;
    }
    `;

  const styleElement = document.createElement("style");

  styleElement.textContent = fontCSS;

  document.head.appendChild(styleElement);
...
```

Appreciate if someone could help me out here

**Comment by bebraw** [comment]
A couple of points:

1. Make sure to enable the related stylistic set. Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_fonts/OpenType_fonts_guide .
2. Script variant is available only for italic behind ss02
3. See how it has been done at https://www.monolisa.dev/specimen . After selecting an italic variant, look for the Script section. You should be able to inspect the source to see how it's getting applied.

**Comment by KoichaDev** [comment]
@bebraw  Fantastic! I got it to work now! Thank you very much for your help! I am a very happy person now! 😁

Btw. I noticed that on your website, you have added values `unicode-ranges`, e.g:

```css
...
@font-face {
  src: url(...) format("woff2");
  font-family: ml;
  font-weight: 100 900;
  font-style: normal;
  unicode-range: U+2387, U+238B, U+2327, U+232B, U+2326, U+23CF, U+2328, U+2325, U+2318, U+23CE, U+23FB, U+23FC, U+23FD, U+23FE, U+2212, U+2260, U+2265, U+2264, U+2248, U+2205, U+221E, U+222B, +220F, U+2211, U+221A, U+2202, U+E0A0, U+E0A1, U+E0A2, U+E0B0, U+E0B1, U+E0B2, U+E0B3, U+EE00, U+EE01, U+EE02, U+EE03, U+EE04, U+EE05, U+EE10, U+EE11, U+EE12, U+EE13, U+EE14, U+EE15;
/*^ here*/
}
...
```

Is it something I should consider to add in as well?
